fix download

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -51,8 +51,19 @@ jobs:
         run: |
           VERSION=${{ steps.get_java_version_clean.outputs.java_version_clean }}
           echo "Downloading mokkyBuddyAPI-${VERSION}.jar"
+
+          # Assicuriamoci che la cartella esista
+          mkdir -p plugin/resources
+
           curl -L -o plugin/resources/mokkyBuddyAPI.jar \
             "https://github.com/stapeDev/it.stapedev.api.mokkybuddy/releases/download/v${VERSION}/mokkyBuddyAPI-${VERSION}.jar"
+
+          # Verifica file
+          if [ ! -f plugin/resources/mokkyBuddyAPI.jar ]; then
+            echo "ERROR: JAR file not downloaded!"
+            ls -la plugin/resources
+            exit 1
+          fi
 
       - name: Install dependencies
         working-directory: plugin
